In [1]:
import numpy as np

arr = np.array([
    [1, 2, 2, 3],
    [3, 3, 4, 4],
    [4, 4, 4, 5],
    [5, 5, 5, 5]
])

# Calculate the threshold count
threshold_count = 5
threshold_count
# Find  unique values and their counts


5

In [2]:
unique_values, counts = np.unique(arr, return_counts=True)
unique_values, counts

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 5, 5], dtype=int64))

In [3]:

# Create a mask for values with a count less than the threshold count
mask = unique_values[counts < threshold_count]
mask
# Replace the elements in the array that match the mask with 0


array([1, 2, 3])

In [4]:
arr[np.isin(arr, mask)] = 0


In [5]:
arr
arr = np.array([
    [1, 1, 2, 3],
    [1, 1, 4, 4],
    [4, 4, 4, 4],
    [5, 5, 5, 5]
])


In [6]:
from service.Service import Service

service = Service()
label_color = service.generate_colors_for_prediction(arr)
label_color

(array([[1, 1, 2, 3],
        [1, 1, 4, 4],
        [4, 4, 4, 4],
        [5, 5, 5, 5]]),
 {2: [255, 0, 0],
  3: [203, 255, 0],
  1: [0, 255, 102],
  5: [0, 101, 255],
  4: [203, 0, 255]})

In [7]:
service.get_bounding_boxes(arr)

[[(0, 0), (1, 1)],
 [(0, 2), (0, 2)],
 [(0, 3), (0, 3)],
 [(1, 0), (2, 3)],
 [(3, 0), (3, 3)]]